import { PlayerIdentity, Stock, ShopItem, Job, Entertainment, GameEvent, CustomDifficulty } from './types';

// 默认自定义难度
export const DEFAULT_CUSTOM_DIFFICULTY: CustomDifficulty = {
  initialCash: 50000,
  stockVolatility: 1,
  survivalDecayRate: 1,
  foodPriceMultiplier: 1,
  workPayMultiplier: 1,
  eventProbability: 1,
};

// 难度配置
export const DIFFICULTY_CONFIG: Record<string, {
  name: string;
  description: string;
  initialCashMultiplier: number;
  stockVolatilityMultiplier: number;
  survivalDecayMultiplier: number;
  eventProbabilityMultiplier: number;
}> = {
  easy: {
    name: '简单',
    description: '适合新手，资金充足，生存压力小',
    initialCashMultiplier: 2,
    stockVolatilityMultiplier: 0.7,
    survivalDecayMultiplier: 0.5,
    eventProbabilityMultiplier: 0.5,
  },
  normal: {
    name: '普通',
    description: '标准难度，平衡的游戏体验',
    initialCashMultiplier: 1,
    stockVolatilityMultiplier: 1,
    survivalDecayMultiplier: 1,
    eventProbabilityMultiplier: 1,
  },
  hard: {
    name: '困难',
    description: '资金紧张，市场波动大，生存压力大',
    initialCashMultiplier: 0.5,
    stockVolatilityMultiplier: 1.5,
    survivalDecayMultiplier: 1.5,
    eventProbabilityMultiplier: 1.5,
  },
  realistic: {
    name: '现实',
    description: '极度真实，资金有限，市场残酷',
    initialCashMultiplier: 0.3,
    stockVolatilityMultiplier: 2,
    survivalDecayMultiplier: 2,
    eventProbabilityMultiplier: 2,
  },
  custom: {
    name: '自定义',
    description: '自由调整各项参数',
    initialCashMultiplier: 1,
    stockVolatilityMultiplier: 1,
    survivalDecayMultiplier: 1,
    eventProbabilityMultiplier: 1,
  },
  cheat: {
    name: '作弊',
    description: '无限资金，体验纯粹的炒股乐趣',
    initialCashMultiplier: 100,
    stockVolatilityMultiplier: 1,
    survivalDecayMultiplier: 0,
    eventProbabilityMultiplier: 0,
  },
};

// 玩家身份列表
export const PLAYER_IDENTITIES: PlayerIdentity[] = [
  {
    id: 'student',
    name: '大学生',
    description: '刚步入社会的年轻人，资金有限但充满希望',
    initialCash: 10000,
    stressResistance: 40,
    workEfficiency: 60,
    investmentSense: 30,
    icon: '🎓',
  },
  {
    id: 'office_worker',
    name: '上班族',
    description: '朝九晚五的打工人，有一定积蓄和工作经验',
    initialCash: 50000,
    stressResistance: 60,
    workEfficiency: 70,
    investmentSense: 50,
    icon: '💼',
  },
  {
    id: 'entrepreneur',
    name: '创业者',
    description: '敢于冒险的创业者，资金充裕但压力巨大',
    initialCash: 200000,
    stressResistance: 80,
    workEfficiency: 90,
    investmentSense: 60,
    icon: '🚀',
  },
  {
    id: 'retiree',
    name: '退休人员',
    description: '退休老人，积蓄丰厚但精力有限',
    initialCash: 300000,
    stressResistance: 30,
    workEfficiency: 30,
    investmentSense: 70,
    icon: '👴',
  },
  {
    id: 'freelancer',
    name: '自由职业者',
    description: '自由自在，收入不稳定但时间灵活',
    initialCash: 30000,
    stressResistance: 50,
    workEfficiency: 80,
    investmentSense: 55,
    icon: '🎨',
  },
  {
    id: 'doctor',
    name: '医生',
    description: '救死扶伤的白衣天使，收入稳定但工作繁忙',
    initialCash: 150000,
    stressResistance: 75,
    workEfficiency: 85,
    investmentSense: 45,
    icon: '👨‍⚕️',
  },
  {
    id: 'teacher',
    name: '教师',
    description: '教书育人的园丁，收入稳定生活规律',
    initialCash: 80000,
    stressResistance: 65,
    workEfficiency: 70,
    investmentSense: 50,
    icon: '👩‍🏫',
  },
  {
    id: 'engineer',
    name: '程序员',
    description: '技术大牛，高薪但工作压力大',
    initialCash: 120000,
    stressResistance: 55,
    workEfficiency: 90,
    investmentSense: 65,
    icon: '👨‍💻',
  },
  {
    id: 'sales',
    name: '销售经理',
    description: '业绩为王，收入波动大但机会多',
    initialCash: 60000,
    stressResistance: 70,
    workEfficiency: 75,
    investmentSense: 60,
    icon: '📊',
  },
  {
    id: 'investor',
    name: '专业投资者',
    description: '股市老手，资金雄厚经验丰富',
    initialCash: 500000,
    stressResistance: 90,
    workEfficiency: 60,
    investmentSense: 95,
    icon: '📈',
  },
  {
    id: 'custom',
    name: '自定义',
    description: '自定义你的身份属性',
    initialCash: 50000,
    stressResistance: 50,
    workEfficiency: 50,
    investmentSense: 50,
    icon: '⚙️',
  },
];

// 行业列表
export const INDUSTRIES = [
  { id: 'tech', name: '科技', description: '高科技行业，波动大但潜力高' },
  { id: 'finance', name: '金融', description: '金融行业，稳定但增长有限' },
  { id: 'realestate', name: '房地产', description: '房地产行业，周期性强' },
  { id: 'consumer', name: '消费', description: '消费行业，需求稳定' },
  { id: 'healthcare', name: '医疗', description: '医疗行业，长期看好' },
  { id: 'energy', name: '能源', description: '能源行业，受政策影响大' },
  { id: 'manufacture', name: '制造', description: '制造业，传统稳健' },
  { id: 'entertainment', name: '娱乐', description: '娱乐行业，波动较大' },
];

// 初始股票列表
export const INITIAL_STOCKS: Stock[] = [
  // 科技股
  {
    id: 'tech001',
    code: 'TECH',
    name: '科技创新集团',
    industry: 'tech',
    basePrice: 88.50,
    currentPrice: 88.50,
    previousPrice: 88.50,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.03,
    trend: 'stable',
    description: '国内领先的科技公司，主营人工智能和云计算',
    history: [],
    totalShares: 100000000,
  },
  {
    id: 'tech002',
    code: 'CHIP',
    name: '芯创半导体',
    industry: 'tech',
    basePrice: 156.20,
    currentPrice: 156.20,
    previousPrice: 156.20,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.04,
    trend: 'stable',
    description: '芯片设计与制造龙头企业',
    history: [],
    totalShares: 50000000,
  },
  {
    id: 'tech003',
    code: 'SOFT',
    name: '软云科技',
    industry: 'tech',
    basePrice: 45.80,
    currentPrice: 45.80,
    previousPrice: 45.80,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.035,
    trend: 'stable',
    description: '企业级软件解决方案提供商',
    history: [],
    totalShares: 80000000,
  },
  // 金融股
  {
    id: 'fin001',
    code: 'BANK',
    name: '国泰银行',
    industry: 'finance',
    basePrice: 12.35,
    currentPrice: 12.35,
    previousPrice: 12.35,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.015,
    trend: 'stable',
    description: '全国性大型商业银行',
    history: [],
    totalShares: 500000000,
  },
  {
    id: 'fin002',
    code: 'SECU',
    name: '华信证券',
    industry: 'finance',
    basePrice: 28.90,
    currentPrice: 28.90,
    previousPrice: 28.90,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.025,
    trend: 'stable',
    description: '综合性证券公司',
    history: [],
    totalShares: 200000000,
  },
  {
    id: 'fin003',
    code: 'INSU',
    name: '平安保险',
    industry: 'finance',
    basePrice: 52.40,
    currentPrice: 52.40,
    previousPrice: 52.40,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.02,
    trend: 'stable',
    description: '大型保险金融集团',
    history: [],
    totalShares: 300000000,
  },
  // 房地产
  {
    id: 'real001',
    code: 'LAND',
    name: '万科地产',
    industry: 'realestate',
    basePrice: 18.60,
    currentPrice: 18.60,
    previousPrice: 18.60,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.025,
    trend: 'stable',
    description: '知名房地产开发企业',
    history: [],
    totalShares: 400000000,
  },
  {
    id: 'real002',
    code: 'BUILD',
    name: '城建集团',
    industry: 'realestate',
    basePrice: 8.95,
    currentPrice: 8.95,
    previousPrice: 8.95,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.03,
    trend: 'stable',
    description: '城市基础设施建设龙头',
    history: [],
    totalShares: 600000000,
  },
  // 消费
  {
    id: 'cons001',
    code: 'FOOD',
    name: '美味食品',
    industry: 'consumer',
    basePrice: 35.20,
    currentPrice: 35.20,
    previousPrice: 35.20,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.015,
    trend: 'stable',
    description: '知名食品饮料企业',
    history: [],
    totalShares: 150000000,
  },
  {
    id: 'cons002',
    code: 'RETAIL',
    name: '优品零售',
    industry: 'consumer',
    basePrice: 22.80,
    currentPrice: 22.80,
    previousPrice: 22.80,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.02,
    trend: 'stable',
    description: '连锁零售巨头',
    history: [],
    totalShares: 250000000,
  },
  // 医疗
  {
    id: 'health001',
    code: 'MED',
    name: '仁和医药',
    industry: 'healthcare',
    basePrice: 68.50,
    currentPrice: 68.50,
    previousPrice: 68.50,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.02,
    trend: 'stable',
    description: '医药研发与生产企业',
    history: [],
    totalShares: 80000000,
  },
  {
    id: 'health002',
    code: 'HOSP',
    name: '康健医疗',
    industry: 'healthcare',
    basePrice: 42.30,
    currentPrice: 42.30,
    previousPrice: 42.30,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.018,
    trend: 'stable',
    description: '医疗服务连锁机构',
    history: [],
    totalShares: 120000000,
  },
  // 能源
  {
    id: 'energy001',
    code: 'OIL',
    name: '中能石油',
    industry: 'energy',
    basePrice: 7.85,
    currentPrice: 7.85,
    previousPrice: 7.85,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.025,
    trend: 'stable',
    description: '大型石油能源企业',
    history: [],
    totalShares: 800000000,
  },
  {
    id: 'energy002',
    code: 'POWER',
    name: '华电集团',
    industry: 'energy',
    basePrice: 15.60,
    currentPrice: 15.60,
    previousPrice: 15.60,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.02,
    trend: 'stable',
    description: '电力生产与供应企业',
    history: [],
    totalShares: 500000000,
  },
  // 制造
  {
    id: 'manu001',
    code: 'AUTO',
    name: '华汽集团',
    industry: 'manufacture',
    basePrice: 25.40,
    currentPrice: 25.40,
    previousPrice: 25.40,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.022,
    trend: 'stable',
    description: '汽车制造龙头企业',
    history: [],
    totalShares: 300000000,
  },
  {
    id: 'manu002',
    code: 'MACH',
    name: '精工机械',
    industry: 'manufacture',
    basePrice: 38.90,
    currentPrice: 38.90,
    previousPrice: 38.90,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.018,
    trend: 'stable',
    description: '高端装备制造企业',
    history: [],
    totalShares: 100000000,
  },
  // 娱乐
  {
    id: 'ent001',
    code: 'GAME',
    name: '畅游游戏',
    industry: 'entertainment',
    basePrice: 55.80,
    currentPrice: 55.80,
    previousPrice: 55.80,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.04,
    trend: 'stable',
    description: '游戏开发与运营企业',
    history: [],
    totalShares: 60000000,
  },
  {
    id: 'ent002',
    code: 'MEDIA',
    name: '传媒集团',
    industry: 'entertainment',
    basePrice: 19.50,
    currentPrice: 19.50,
    previousPrice: 19.50,
    dayChange: 0,
    dayChangePercent: 0,
    volatility: 0.035,
    trend: 'stable',
    description: '综合性传媒娱乐企业',
    history: [],
    totalShares: 200000000,
  },
];

// 商店物品
export const SHOP_ITEMS: ShopItem[] = [
  // 食物
  {
    id: 'food001',
    name: '面包',
    type: 'food',
    price: 5,
    effect: { hunger: 15 },
    shelfLife: 7,
    description: '普通面包，充饥必备',
    icon: '🍞',
  },
  {
    id: 'food002',
    name: '便当',
    type: 'food',
    price: 25,
    effect: { hunger: 40, mood: 5 },
    shelfLife: 1,
    description: '营养均衡的便当',
    icon: '🍱',
  },
  {
    id: 'food003',
    name: '泡面',
    type: 'food',
    price: 8,
    effect: { hunger: 25, health: -5 },
    shelfLife: 180,
    description: '方便快捷但不健康',
    icon: '🍜',
  },
  {
    id: 'food004',
    name: '水果',
    type: 'food',
    price: 15,
    effect: { hunger: 10, health: 10, mood: 5 },
    shelfLife: 5,
    description: '新鲜水果，健康美味',
    icon: '🍎',
  },
  {
    id: 'food005',
    name: '大餐',
    type: 'food',
    price: 100,
    effect: { hunger: 80, mood: 30, health: 5 },
    shelfLife: 0,
    description: '高档餐厅大餐，立即享用',
    icon: '🍽️',
  },
  {
    id: 'food006',
    name: '快餐',
    type: 'food',
    price: 30,
    effect: { hunger: 50, mood: 10 },
    shelfLife: 0,
    description: '快餐店套餐，立即享用',
    icon: '🍔',
  },
  // 饮品
  {
    id: 'drink001',
    name: '矿泉水',
    type: 'drink',
    price: 2,
    effect: { thirst: 20 },
    shelfLife: 365,
    description: '纯净水，解渴必备',
    icon: '💧',
  },
  {
    id: 'drink002',
    name: '可乐',
    type: 'drink',
    price: 5,
    effect: { thirst: 25, mood: 5, health: -3 },
    shelfLife: 365,
    description: '碳酸饮料，快乐水',
    icon: '🥤',
  },
  {
    id: 'drink003',
    name: '咖啡',
    type: 'drink',
    price: 20,
    effect: { thirst: 10, mood: 15 },
    shelfLife: 30,
    description: '提神醒脑的咖啡',
    icon: '☕',
  },
  {
    id: 'drink004',
    name: '奶茶',
    type: 'drink',
    price: 18,
    effect: { thirst: 20, mood: 20, hunger: 5 },
    shelfLife: 1,
    description: '网红奶茶，快乐加倍',
    icon: '🧋',
  },
  {
    id: 'drink005',
    name: '果汁',
    type: 'drink',
    price: 12,
    effect: { thirst: 30, health: 5, mood: 5 },
    shelfLife: 3,
    description: '鲜榨果汁，健康饮品',
    icon: '🧃',
  },
  // 药品
  {
    id: 'med001',
    name: '感冒药',
    type: 'medicine',
    price: 15,
    effect: { health: 20 },
    shelfLife: 730,
    description: '治疗感冒，恢复健康',
    icon: '💊',
  },
  {
    id: 'med002',
    name: '维生素',
    type: 'medicine',
    price: 50,
    effect: { health: 30, mood: 5 },
    shelfLife: 730,
    description: '补充营养，增强体质',
    icon: '💊',
  },
  {
    id: 'med003',
    name: '体检套餐',
    type: 'medicine',
    price: 300,
    effect: { health: 50, mood: 10 },
    shelfLife: 0,
    description: '全面体检，了解身体状况',
    icon: '🏥',
  },
  // 娱乐
  {
    id: 'ent_item001',
    name: '电影票',
    type: 'entertainment',
    price: 50,
    effect: { mood: 25 },
    shelfLife: 30,
    description: '看场电影放松一下',
    icon: '🎬',
  },
  {
    id: 'ent_item002',
    name: '游戏充值卡',
    type: 'entertainment',
    price: 100,
    effect: { mood: 40 },
    shelfLife: 365,
    description: '游戏充值，快乐加倍',
    icon: '🎮',
  },
];

// 工作列表
export const JOBS: Job[] = [
  {
    id: 'job001',
    name: '送外卖',
    description: '骑手送餐，按单计费',
    hourlyPay: 25,
    energyCost: 15,
    moodEffect: -5,
    requiredHealth: 30,
    workHours: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
  },
  {
    id: 'job002',
    name: '便利店兼职',
    description: '便利店收银理货',
    hourlyPay: 18,
    energyCost: 10,
    moodEffect: -3,
    requiredHealth: 20,
    workHours: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
  },
  {
    id: 'job003',
    name: '家教',
    description: '辅导学生功课',
    hourlyPay: 80,
    energyCost: 12,
    moodEffect: 5,
    requiredHealth: 40,
    workHours: [16, 17, 18, 19, 20, 21],
  },
  {
    id: 'job004',
    name: '网约车司机',
    description: '开网约车接单',
    hourlyPay: 40,
    energyCost: 12,
    moodEffect: -5,
    requiredHealth: 50,
    workHours: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
  },
  {
    id: 'job005',
    name: '网络写手',
    description: '在家写作赚钱',
    hourlyPay: 35,
    energyCost: 8,
    moodEffect: 0,
    requiredHealth: 20,
    workHours: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
  },
  {
    id: 'job006',
    name: '直播带货',
    description: '网络直播销售',
    hourlyPay: 60,
    energyCost: 15,
    moodEffect: 10,
    requiredHealth: 50,
    workHours: [18, 19, 20, 21, 22, 23, 0],
  },
  {
    id: 'job007',
    name: '设计接单',
    description: '接设计项目赚钱',
    hourlyPay: 100,
    energyCost: 10,
    moodEffect: 5,
    requiredHealth: 30,
    workHours: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
  },
  {
    id: 'job008',
    name: '夜班保安',
    description: '夜间值班巡逻',
    hourlyPay: 30,
    energyCost: 5,
    moodEffect: -10,
    requiredHealth: 40,
    workHours: [22, 23, 0, 1, 2, 3, 4, 5],
  },
];

// 娱乐设施
export const ENTERTAINMENTS: Entertainment[] = [
  {
    id: 'ent001',
    name: '网吧上网',
    description: '去网吧打游戏',
    cost: 15,
    moodBoost: 20,
    timeCost: 3,
    icon: '🖥️',
  },
  {
    id: 'ent002',
    name: 'KTV唱歌',
    description: '和朋友去KTV',
    cost: 80,
    moodBoost: 35,
    timeCost: 3,
    icon: '🎤',
  },
  {
    id: 'ent003',
    name: '健身房',
    description: '去健身房锻炼',
    cost: 50,
    moodBoost: 20,
    timeCost: 2,
    icon: '🏋️',
  },
  {
    id: 'ent004',
    name: '游乐园',
    description: '去游乐园玩一天',
    cost: 200,
    moodBoost: 50,
    timeCost: 6,
    icon: '🎢',
  },
  {
    id: 'ent005',
    name: '按摩SPA',
    description: '放松身心的按摩',
    cost: 150,
    moodBoost: 40,
    timeCost: 2,
    icon: '💆',
  },
  {
    id: 'ent006',
    name: '逛街购物',
    description: '去商场逛街购物',
    cost: 100,
    moodBoost: 30,
    timeCost: 4,
    icon: '🛍️',
  },
  {
    id: 'ent007',
    name: '公园散步',
    description: '去公园散步放松',
    cost: 0,
    moodBoost: 15,
    timeCost: 1,
    icon: '🌳',
  },
  {
    id: 'ent008',
    name: '看书学习',
    description: '在家看书充电',
    cost: 0,
    moodBoost: 10,
    timeCost: 2,
    icon: '📚',
  },
];

// 随机事件
export const GAME_EVENTS: GameEvent[] = [
  // 正面事件
  {
    id: 'event001',
    title: '意外之财',
    description: '你在街上捡到了一个钱包！',
    type: 'positive',
    effects: { cash: 500 },
    probability: 0.02,
  },
  {
    id: 'event002',
    title: '股票分红',
    description: '你持有的股票发放了分红！',
    type: 'positive',
    effects: { cash: 1000, mood: 10 },
    probability: 0.03,
  },
  {
    id: 'event003',
    title: '朋友请客',
    description: '朋友请你吃了一顿大餐！',
    type: 'positive',
    effects: { hunger: 30, mood: 20 },
    probability: 0.03,
  },
  {
    id: 'event004',
    title: '科技利好',
    description: '国家出台科技产业扶持政策！',
    type: 'positive',
    effects: { stockEffect: { industry: 'tech', effect: 5 } },
    probability: 0.02,
  },
  {
    id: 'event005',
    title: '医疗突破',
    description: '医疗行业取得重大突破！',
    type: 'positive',
    effects: { stockEffect: { industry: 'healthcare', effect: 8 } },
    probability: 0.015,
  },
  // 负面事件
  {
    id: 'event006',
    title: '手机坏了',
    description: '你的手机突然坏了，需要维修',
    type: 'negative',
    effects: { cash: -800, mood: -15 },
    probability: 0.02,
  },
  {
    id: 'event007',
    title: '生病了',
    description: '你感冒了，需要看医生',
    type: 'negative',
    effects: { cash: -200, health: -20, mood: -20 },
    probability: 0.025,
  },
  {
    id: 'event008',
    title: '股市暴跌',
    description: '市场恐慌情绪蔓延，股市大跌！',
    type: 'negative',
    effects: { mood: -25, stockEffect: { effect: -8 } },
    probability: 0.02,
  },
  {
    id: 'event009',
    title: '行业危机',
    description: '房地产行业遭遇政策调控！',
    type: 'negative',
    effects: { stockEffect: { industry: 'realestate', effect: -10 } },
    probability: 0.015,
  },
  {
    id: 'event010',
    title: '丢钱包',
    description: '你不小心丢了钱包',
    type: 'negative',
    effects: { cash: -300, mood: -20 },
    probability: 0.02,
  },
  // 中性事件
  {
    id: 'event011',
    title: '老友来访',
    description: '老朋友突然来访，聊得很开心',
    type: 'neutral',
    effects: { mood: 15, hunger: -10 },
    probability: 0.03,
  },
  {
    id: 'event012',
    title: '天气变化',
    description: '天气突然变化，注意身体',
    type: 'neutral',
    effects: { health: -5 },
    probability: 0.04,
  },
];

// 存档相关常量
export const MAX_SAVE_SLOTS = 100;
export const SAVE_KEY_PREFIX = 'stock_game_save_';
export const AUTO_SAVE_INTERVAL = 60000; // 自动存档间隔（毫秒）
