import { News, NewsCategory, NewsImportance } from './types';

// 新闻模板
export interface NewsTemplate {
  id: string;
  titleTemplate: string;
  contentTemplate: string;
  category: NewsCategory;
  importance: NewsImportance;
  type: 'positive' | 'negative' | 'neutral';
  effectRange: {
    min: number;
    max: number;
  };
  durationRange: {
    min: number; // 最少持续小时数
    max: number; // 最多持续小时数
  };
  affectedIndustries?: string[]; // 影响的行业，空表示影响大盘
  affectedStockIds?: string[]; // 影响的个股
  marketEffectRange?: {
    min: number;
    max: number;
  };
  sentimentEffectRange?: {
    min: number;
    max: number;
  };
  isBreaking?: boolean;
  source: string;
}

// 新闻来源
export const NEWS_SOURCES = [
  '财经日报',
  '证券时报',
  '经济观察报',
  '金融时报',
  '央视财经',
  '新华财经',
  '第一财经',
  '财新网',
  '华尔街见闻',
  '彭博社',
  '路透社',
  '上海证券报',
  '中国证券报',
];

// 宏观经济新闻模板
export const MACRO_ECONOMY_NEWS: NewsTemplate[] = [
  // 正面新闻
  {
    id: 'macro_pos_001',
    titleTemplate: '央行宣布降准{percent}个百分点，释放长期资金约{amount}亿元',
    contentTemplate: '中国人民银行决定于{date}日下调金融机构存款准备金率{percent}个百分点，此次降准释放长期资金约{amount}亿元，将有效增加金融机构支持实体经济的稳定资金来源。分析人士认为，此举将有效提振市场信心，促进经济平稳健康发展。',
    category: 'macro_economy',
    importance: 'critical',
    type: 'positive',
    effectRange: { min: 2, max: 5 },
    durationRange: { min: 24, max: 72 },
    marketEffectRange: { min: 1, max: 3 },
    sentimentEffectRange: { min: 20, max: 40 },
    isBreaking: true,
    source: '央视财经',
  },
  {
    id: 'macro_pos_002',
    titleTemplate: 'GDP同比增长{percent}%，经济复苏势头强劲',
    contentTemplate: '国家统计局公布数据显示，{quarter}季度国内生产总值(GDP)同比增长{percent}%，超出市场预期。消费、投资、出口三驾马车协同发力，经济运行延续恢复向好的态势。专家表示，经济基本面持续向好，为资本市场提供了有力支撑。',
    category: 'macro_economy',
    importance: 'major',
    type: 'positive',
    effectRange: { min: 1, max: 3 },
    durationRange: { min: 12, max: 48 },
    marketEffectRange: { min: 0.5, max: 2 },
    sentimentEffectRange: { min: 15, max: 30 },
    source: '新华财经',
  },
  {
    id: 'macro_pos_003',
    titleTemplate: '制造业PMI升至{value}，连续{months}个月位于扩张区间',
    contentTemplate: '{month}月份中国制造业采购经理指数(PMI)为{value}%，比上月上升{change}个百分点，连续{months}个月位于扩张区间。制造业景气面继续扩大，企业生产经营活动预期向好，经济恢复动力持续增强。',
    category: 'macro_economy',
    importance: 'major',
    type: 'positive',
    effectRange: { min: 1, max: 2 },
    durationRange: { min: 8, max: 24 },
    affectedIndustries: ['manufacture'],
    marketEffectRange: { min: 0.3, max: 1 },
    sentimentEffectRange: { min: 10, max: 20 },
    source: '经济观察报',
  },
  {
    id: 'macro_pos_004',
    titleTemplate: '社会消费品零售总额同比增长{percent}%，消费市场持续回暖',
    contentTemplate: '国家统计局数据显示，{month}月份社会消费品零售总额同比增长{percent}%，增速比上月加快{change}个百分点。消费市场延续恢复态势，餐饮、旅游、文娱等服务消费明显回暖，居民消费信心逐步恢复。',
    category: 'macro_economy',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 0.5, max: 2 },
    durationRange: { min: 6, max: 18 },
    affectedIndustries: ['consumer', 'entertainment'],
    sentimentEffectRange: { min: 5, max: 15 },
    source: '第一财经',
  },
  // 负面新闻
  {
    id: 'macro_neg_001',
    titleTemplate: '央行意外加息{percent}个百分点，市场流动性趋紧',
    contentTemplate: '中国人民银行宣布上调金融机构存贷款基准利率{percent}个百分点，此举超出市场预期。分析人士认为，加息将收紧市场流动性，对股市形成一定压力，投资者需关注后续政策走向。',
    category: 'macro_economy',
    importance: 'critical',
    type: 'negative',
    effectRange: { min: -3, max: -1 },
    durationRange: { min: 24, max: 72 },
    marketEffectRange: { min: -2, max: -0.5 },
    sentimentEffectRange: { min: -40, max: -20 },
    isBreaking: true,
    source: '财经日报',
  },
  {
    id: 'macro_neg_002',
    titleTemplate: 'CPI同比上涨{percent}%，通胀压力引发市场担忧',
    contentTemplate: '国家统计局数据显示，{month}月份全国居民消费价格指数(CPI)同比上涨{percent}%，涨幅比上月扩大{change}个百分点。通胀压力上升引发市场对货币政策收紧的担忧，投资者情绪趋于谨慎。',
    category: 'macro_economy',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -2, max: -0.5 },
    durationRange: { min: 12, max: 36 },
    marketEffectRange: { min: -1, max: -0.3 },
    sentimentEffectRange: { min: -25, max: -10 },
    source: '证券时报',
  },
  {
    id: 'macro_neg_003',
    titleTemplate: '进出口数据不及预期，外贸形势严峻',
    contentTemplate: '海关总署公布数据显示，{month}月份我国进出口总值同比下降{percent}%，其中出口下降{export_percent}%，进口下降{import_percent}%。外贸数据不及预期，反映出外部需求疲软，经济下行压力加大。',
    category: 'macro_economy',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -2, max: -0.5 },
    durationRange: { min: 12, max: 36 },
    marketEffectRange: { min: -1, max: -0.3 },
    sentimentEffectRange: { min: -20, max: -8 },
    source: '财新网',
  },
  // 中性新闻
  {
    id: 'macro_neu_001',
    titleTemplate: '央行公开市场操作净投放{amount}亿元',
    contentTemplate: '人民银行今日开展{operation}亿元逆回购操作，中标利率{rate}%。当日有{due}亿元逆回购到期，实现净投放{amount}亿元。市场流动性保持合理充裕，资金面总体平稳。',
    category: 'macro_economy',
    importance: 'minor',
    type: 'neutral',
    effectRange: { min: -0.3, max: 0.3 },
    durationRange: { min: 2, max: 8 },
    source: '金融时报',
  },
];

// 行业动态新闻模板
export const INDUSTRY_NEWS: NewsTemplate[] = [
  // 科技行业
  {
    id: 'industry_tech_001',
    titleTemplate: '国家出台人工智能产业发展规划，AI产业迎来重大利好',
    contentTemplate: '国务院印发《新一代人工智能发展规划》，提出到2030年使中国人工智能理论、技术与应用总体达到世界领先水平。规划明确了人工智能发展的战略目标、重点任务和保障措施，将为AI产业发展提供强有力的政策支持。',
    category: 'industry',
    importance: 'major',
    type: 'positive',
    effectRange: { min: 3, max: 8 },
    durationRange: { min: 24, max: 72 },
    affectedIndustries: ['tech'],
    sentimentEffectRange: { min: 15, max: 30 },
    source: '新华财经',
  },
  {
    id: 'industry_tech_002',
    titleTemplate: '芯片国产化取得重大突破，自主研发能力显著提升',
    contentTemplate: '国内芯片企业成功研发出具有自主知识产权的高端芯片，性能达到国际先进水平。这一突破标志着我国在芯片领域的技术实力迈上新台阶，将有效降低对进口芯片的依赖，推动产业链自主可控。',
    category: 'industry',
    importance: 'major',
    type: 'positive',
    effectRange: { min: 4, max: 10 },
    durationRange: { min: 24, max: 96 },
    affectedIndustries: ['tech'],
    sentimentEffectRange: { min: 20, max: 40 },
    source: '第一财经',
  },
  {
    id: 'industry_tech_003',
    titleTemplate: '科技巨头遭遇反垄断调查，行业监管趋严',
    contentTemplate: '市场监管总局对多家科技企业启动反垄断调查，重点调查是否存在滥用市场支配地位、不正当竞争等行为。分析人士认为，监管趋严将对科技企业的盈利能力产生一定影响，短期内股价可能承压。',
    category: 'industry',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -5, max: -2 },
    durationRange: { min: 24, max: 72 },
    affectedIndustries: ['tech'],
    sentimentEffectRange: { min: -30, max: -15 },
    source: '财经日报',
  },
  // 医疗行业
  {
    id: 'industry_health_001',
    titleTemplate: '创新药获批上市，医药行业迎来发展新机遇',
    contentTemplate: '国家药监局批准多款创新药物上市，涵盖肿瘤、心血管、神经系统等多个治疗领域。创新药的获批将为患者提供更多治疗选择，同时也为医药企业带来新的增长点，推动行业高质量发展。',
    category: 'industry',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 2, max: 5 },
    durationRange: { min: 12, max: 36 },
    affectedIndustries: ['healthcare'],
    sentimentEffectRange: { min: 10, max: 20 },
    source: '中国证券报',
  },
  {
    id: 'industry_health_002',
    titleTemplate: '医保目录调整，多款药品纳入报销范围',
    contentTemplate: '国家医保局公布新版医保药品目录，新增{count}种药品纳入报销范围，其中包括多款高价创新药。此次调整将显著降低患者用药负担，同时也为相关医药企业带来市场扩容机会。',
    category: 'industry',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 1, max: 3 },
    durationRange: { min: 12, max: 36 },
    affectedIndustries: ['healthcare'],
    sentimentEffectRange: { min: 8, max: 15 },
    source: '证券时报',
  },
  {
    id: 'industry_health_003',
    titleTemplate: '药品集采降价幅度超预期，医药企业利润承压',
    contentTemplate: '新一轮药品集中带量采购结果出炉，多款药品降价幅度超过{percent}%，部分药品降幅甚至超过80%。分析人士指出，集采常态化将压缩医药企业利润空间，行业竞争格局面临重塑。',
    category: 'industry',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -4, max: -1 },
    durationRange: { min: 24, max: 72 },
    affectedIndustries: ['healthcare'],
    sentimentEffectRange: { min: -25, max: -10 },
    source: '经济观察报',
  },
  // 能源行业
  {
    id: 'industry_energy_001',
    titleTemplate: '新能源补贴政策延续，光伏风电行业迎利好',
    contentTemplate: '财政部、发改委联合发布通知，明确新能源补贴政策将继续执行，光伏、风电项目可按规定享受补贴。政策的延续将稳定行业发展预期，促进新能源产业持续健康发展。',
    category: 'industry',
    importance: 'major',
    type: 'positive',
    effectRange: { min: 2, max: 6 },
    durationRange: { min: 24, max: 72 },
    affectedIndustries: ['energy'],
    sentimentEffectRange: { min: 15, max: 30 },
    source: '新华财经',
  },
  {
    id: 'industry_energy_002',
    titleTemplate: '国际油价大涨{percent}%，能源股集体走强',
    contentTemplate: '受地缘政治因素影响，国际原油价格大幅上涨，布伦特原油期货价格突破{price}美元/桶。油价上涨将提升石油企业盈利预期，能源板块受到资金追捧。',
    category: 'industry',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 2, max: 5 },
    durationRange: { min: 8, max: 24 },
    affectedIndustries: ['energy'],
    sentimentEffectRange: { min: 10, max: 20 },
    source: '华尔街见闻',
  },
  {
    id: 'industry_energy_003',
    titleTemplate: '碳中和目标加速推进，传统能源企业转型压力加大',
    contentTemplate: '国务院发布碳达峰碳中和工作意见，明确提出要严格控制化石能源消费，推动能源结构转型。传统能源企业面临转型升级压力，需加快布局清洁能源业务。',
    category: 'industry',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -3, max: -1 },
    durationRange: { min: 24, max: 72 },
    affectedIndustries: ['energy'],
    sentimentEffectRange: { min: -15, max: -5 },
    source: '央视财经',
  },
  // 房地产行业
  {
    id: 'industry_realestate_001',
    titleTemplate: '多地出台楼市松绑政策，房地产市场迎来政策底',
    contentTemplate: '近期多个城市相继出台房地产调控松绑政策，包括降低首付比例、放松限购限贷等。分析人士认为，政策底已经出现，房地产市场有望逐步企稳回暖。',
    category: 'industry',
    importance: 'major',
    type: 'positive',
    effectRange: { min: 2, max: 5 },
    durationRange: { min: 24, max: 72 },
    affectedIndustries: ['realestate'],
    sentimentEffectRange: { min: 15, max: 25 },
    source: '第一财经',
  },
  {
    id: 'industry_realestate_002',
    titleTemplate: '房地产调控政策加码，房企融资渠道收紧',
    contentTemplate: '监管部门进一步收紧房地产企业融资，对房企有息负债实施严格管控。政策加码将加速行业洗牌，部分高杠杆房企面临较大资金压力。',
    category: 'industry',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -5, max: -2 },
    durationRange: { min: 24, max: 96 },
    affectedIndustries: ['realestate'],
    sentimentEffectRange: { min: -30, max: -15 },
    source: '财经日报',
  },
  // 金融行业
  {
    id: 'industry_finance_001',
    titleTemplate: '银行股获准提高分红比例，高股息策略受追捧',
    contentTemplate: '监管部门鼓励银行提高现金分红比例，多家银行宣布提升年度分红方案。高股息策略受到投资者青睐，银行板块估值有望修复。',
    category: 'industry',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 1, max: 3 },
    durationRange: { min: 12, max: 36 },
    affectedIndustries: ['finance'],
    sentimentEffectRange: { min: 10, max: 20 },
    source: '上海证券报',
  },
  {
    id: 'industry_finance_002',
    titleTemplate: '券商行业迎来并购重组潮，行业集中度提升',
    contentTemplate: '多家券商宣布并购重组计划，行业整合加速推进。分析人士认为，并购重组将提升券商综合实力和竞争力，行业龙头将受益于集中度提升。',
    category: 'industry',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 1, max: 4 },
    durationRange: { min: 12, max: 48 },
    affectedIndustries: ['finance'],
    sentimentEffectRange: { min: 8, max: 18 },
    source: '证券时报',
  },
  // 消费行业
  {
    id: 'industry_consumer_001',
    titleTemplate: '消费升级趋势明显，高端消费品需求旺盛',
    contentTemplate: '随着居民收入水平提高，消费升级趋势日益明显。高端食品、品牌服装、智能家电等消费品需求持续旺盛，相关企业业绩增长强劲。',
    category: 'industry',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 1, max: 3 },
    durationRange: { min: 12, max: 36 },
    affectedIndustries: ['consumer'],
    sentimentEffectRange: { min: 8, max: 15 },
    source: '经济观察报',
  },
  {
    id: 'industry_consumer_002',
    titleTemplate: '食品安全事件引发关注，相关企业股价受挫',
    contentTemplate: '某知名食品企业被曝出食品安全问题，引发社会广泛关注。监管部门已介入调查，涉事企业面临处罚和声誉损失，股价大幅下跌。',
    category: 'industry',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -6, max: -2 },
    durationRange: { min: 24, max: 72 },
    affectedIndustries: ['consumer'],
    sentimentEffectRange: { min: -25, max: -10 },
    source: '央视财经',
  },
  // 制造业
  {
    id: 'industry_manufacture_001',
    titleTemplate: '新能源汽车销量创新高，产业链景气度持续',
    contentTemplate: '新能源汽车销量持续攀升，{month}月份销量达到{amount}万辆，同比增长{percent}%。产业链上下游企业订单饱满，业绩增长预期强劲。',
    category: 'industry',
    importance: 'major',
    type: 'positive',
    effectRange: { min: 2, max: 5 },
    durationRange: { min: 12, max: 48 },
    affectedIndustries: ['manufacture'],
    sentimentEffectRange: { min: 15, max: 30 },
    source: '第一财经',
  },
  {
    id: 'industry_manufacture_002',
    titleTemplate: '原材料价格大幅上涨，制造业成本压力加大',
    contentTemplate: '近期钢铁、有色金属等原材料价格大幅上涨，制造业企业成本压力明显加大。部分企业已开始上调产品价格，但利润空间仍受到挤压。',
    category: 'industry',
    importance: 'normal',
    type: 'negative',
    effectRange: { min: -2, max: -0.5 },
    durationRange: { min: 12, max: 36 },
    affectedIndustries: ['manufacture'],
    sentimentEffectRange: { min: -15, max: -5 },
    source: '财新网',
  },
];

// 公司新闻模板
export const COMPANY_NEWS: NewsTemplate[] = [
  {
    id: 'company_pos_001',
    titleTemplate: '{company}发布业绩预告，净利润同比增长{percent}%',
    contentTemplate: '{company}发布业绩预告，预计{year}年净利润同比增长{percent}%至{amount}亿元。公司表示，业绩增长主要得益于主营业务持续向好、市场份额稳步提升。',
    category: 'company',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 2, max: 6 },
    durationRange: { min: 8, max: 24 },
    sentimentEffectRange: { min: 10, max: 20 },
    source: '中国证券报',
  },
  {
    id: 'company_pos_002',
    titleTemplate: '{company}获得重大订单，合同金额达{amount}亿元',
    contentTemplate: '{company}公告称，公司近日收到{client}的中标通知书，中标项目合同金额约{amount}亿元。该项目的实施将对公司经营业绩产生积极影响。',
    category: 'company',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 2, max: 5 },
    durationRange: { min: 8, max: 24 },
    sentimentEffectRange: { min: 8, max: 18 },
    source: '证券时报',
  },
  {
    id: 'company_pos_003',
    titleTemplate: '{company}成功研发新产品，技术达到国际领先水平',
    contentTemplate: '{company}宣布成功研发{product}新产品，经专家鉴定技术达到国际领先水平。新产品的推出将增强公司核心竞争力，有望打开新的市场空间。',
    category: 'company',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 2, max: 5 },
    durationRange: { min: 12, max: 36 },
    sentimentEffectRange: { min: 10, max: 20 },
    source: '第一财经',
  },
  {
    id: 'company_pos_004',
    titleTemplate: '{company}宣布高比例分红，每{unit}股派发现金红利{amount}元',
    contentTemplate: '{company}发布分红公告，拟每{unit}股派发现金红利{amount}元，合计派发现金红利总额{total}亿元，分红比例高达{percent}%。',
    category: 'company',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 1, max: 3 },
    durationRange: { min: 6, max: 18 },
    sentimentEffectRange: { min: 8, max: 15 },
    source: '上海证券报',
  },
  {
    id: 'company_neg_001',
    titleTemplate: '{company}业绩大幅下滑，净利润同比下降{percent}%',
    contentTemplate: '{company}发布业绩预告，预计{year}年净利润同比下降{percent}%。公司表示，业绩下滑主要受市场环境变化、原材料成本上涨等因素影响。',
    category: 'company',
    importance: 'normal',
    type: 'negative',
    effectRange: { min: -5, max: -2 },
    durationRange: { min: 8, max: 24 },
    sentimentEffectRange: { min: -20, max: -8 },
    source: '财经日报',
  },
  {
    id: 'company_neg_002',
    titleTemplate: '{company}收到监管问询函，涉嫌信息披露违规',
    contentTemplate: '{company}公告称收到交易所问询函，要求公司就{issue}相关问题作出说明。监管层对信息披露违规行为保持高压态势，投资者需关注后续进展。',
    category: 'company',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -6, max: -2 },
    durationRange: { min: 12, max: 48 },
    sentimentEffectRange: { min: -25, max: -10 },
    source: '证券时报',
  },
  {
    id: 'company_neg_003',
    titleTemplate: '{company}高管减持套现{amount}亿元，引发市场关注',
    contentTemplate: '{company}公告显示，公司高管{executive}减持公司股份{shares}万股，套现金额约{amount}亿元。高管减持行为引发市场对公司发展前景的担忧。',
    category: 'company',
    importance: 'normal',
    type: 'negative',
    effectRange: { min: -3, max: -1 },
    durationRange: { min: 8, max: 24 },
    sentimentEffectRange: { min: -15, max: -5 },
    source: '经济观察报',
  },
  {
    id: 'company_neg_004',
    titleTemplate: '{company}产品质量问题被曝光，品牌形象受损',
    contentTemplate: '媒体报道{company}产品存在质量问题，引发消费者投诉。公司已启动应急预案，对相关产品进行召回。事件对公司品牌形象和销售业绩将产生负面影响。',
    category: 'company',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -8, max: -3 },
    durationRange: { min: 24, max: 72 },
    sentimentEffectRange: { min: -30, max: -15 },
    source: '央视财经',
  },
];

// 政策法规新闻模板
export const POLICY_NEWS: NewsTemplate[] = [
  {
    id: 'policy_pos_001',
    titleTemplate: '国务院出台稳增长政策组合拳，多措并举提振经济',
    contentTemplate: '国务院常务会议部署稳经济一揽子政策措施，涵盖财政、金融、稳产业链供应链、促消费和投资等六个方面33项措施。政策力度超出市场预期，将有效稳定经济大盘。',
    category: 'policy',
    importance: 'critical',
    type: 'positive',
    effectRange: { min: 2, max: 5 },
    durationRange: { min: 48, max: 120 },
    marketEffectRange: { min: 1, max: 3 },
    sentimentEffectRange: { min: 25, max: 45 },
    isBreaking: true,
    source: '新华财经',
  },
  {
    id: 'policy_pos_002',
    titleTemplate: '资本市场改革深化，注册制全面落地',
    contentTemplate: '全面实行股票发行注册制改革正式启动，标志着资本市场基础制度改革取得重大突破。改革将提升市场效率，优化资源配置，为实体经济发展提供更有力的支持。',
    category: 'policy',
    importance: 'critical',
    type: 'positive',
    effectRange: { min: 1, max: 3 },
    durationRange: { min: 48, max: 96 },
    marketEffectRange: { min: 0.5, max: 2 },
    sentimentEffectRange: { min: 20, max: 35 },
    source: '中国证券报',
  },
  {
    id: 'policy_neg_001',
    titleTemplate: '行业监管政策收紧，相关企业面临合规压力',
    contentTemplate: '监管部门发布{industry}行业新规，对行业准入、经营行为、信息披露等方面提出更严格要求。新规实施将对相关企业经营产生一定影响，行业整合加速。',
    category: 'policy',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -4, max: -1 },
    durationRange: { min: 24, max: 72 },
    sentimentEffectRange: { min: -25, max: -10 },
    source: '财经日报',
  },
];

// 国际形势新闻模板
export const INTERNATIONAL_NEWS: NewsTemplate[] = [
  {
    id: 'intl_pos_001',
    titleTemplate: '中美贸易谈判取得积极进展，市场情绪回暖',
    contentTemplate: '中美两国就经贸问题进行磋商，双方同意继续推进谈判进程。谈判取得积极进展，市场对贸易关系改善的预期升温，风险偏好有所回升。',
    category: 'international',
    importance: 'critical',
    type: 'positive',
    effectRange: { min: 2, max: 4 },
    durationRange: { min: 24, max: 72 },
    marketEffectRange: { min: 1, max: 2.5 },
    sentimentEffectRange: { min: 20, max: 40 },
    isBreaking: true,
    source: '华尔街见闻',
  },
  {
    id: 'intl_neg_001',
    titleTemplate: '地缘政治紧张局势升级，全球市场避险情绪升温',
    contentTemplate: '国际地缘政治紧张局势升级，投资者避险情绪明显升温。全球股市普遍下跌，黄金、美元等避险资产受到追捧。市场波动性加大，投资者需保持谨慎。',
    category: 'international',
    importance: 'critical',
    type: 'negative',
    effectRange: { min: -3, max: -1 },
    durationRange: { min: 24, max: 96 },
    marketEffectRange: { min: -2, max: -0.5 },
    sentimentEffectRange: { min: -40, max: -20 },
    isBreaking: true,
    source: '彭博社',
  },
  {
    id: 'intl_neg_002',
    titleTemplate: '美联储加息预期升温，全球流动性收紧',
    contentTemplate: '美联储会议纪要显示，多数官员支持继续加息以抑制通胀。市场预期美联储将在下次会议上加息{percent}个基点。全球流动性收紧预期对风险资产形成压力。',
    category: 'international',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -2, max: -0.5 },
    durationRange: { min: 24, max: 72 },
    marketEffectRange: { min: -1.5, max: -0.3 },
    sentimentEffectRange: { min: -25, max: -10 },
    source: '路透社',
  },
  {
    id: 'intl_neg_003',
    titleTemplate: '国际贸易摩擦加剧，出口企业面临挑战',
    contentTemplate: '多国贸易保护主义抬头，国际贸易摩擦加剧。我国出口企业面临关税壁垒、技术封锁等多重挑战，外贸形势趋于复杂。',
    category: 'international',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -2, max: -0.5 },
    durationRange: { min: 24, max: 72 },
    marketEffectRange: { min: -1, max: -0.3 },
    sentimentEffectRange: { min: -20, max: -8 },
    source: '财新网',
  },
];

// 市场情绪新闻模板
export const MARKET_SENTIMENT_NEWS: NewsTemplate[] = [
  {
    id: 'sentiment_pos_001',
    titleTemplate: '北向资金连续{days}日净流入，外资看好A股前景',
    contentTemplate: '北向资金今日净买入{amount}亿元，已连续{days}个交易日实现净流入。外资持续流入显示对A股市场的信心，市场情绪得到提振。',
    category: 'market_sentiment',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 0.5, max: 2 },
    durationRange: { min: 6, max: 18 },
    marketEffectRange: { min: 0.3, max: 1 },
    sentimentEffectRange: { min: 10, max: 20 },
    source: '证券时报',
  },
  {
    id: 'sentiment_pos_002',
    titleTemplate: '两市成交额突破{amount}万亿，市场活跃度提升',
    contentTemplate: '今日沪深两市成交额突破{amount}万亿元，创近期新高。市场交投活跃，投资者参与热情高涨，显示市场信心正在恢复。',
    category: 'market_sentiment',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 0.5, max: 1.5 },
    durationRange: { min: 4, max: 12 },
    marketEffectRange: { min: 0.2, max: 0.8 },
    sentimentEffectRange: { min: 8, max: 15 },
    source: '第一财经',
  },
  {
    id: 'sentiment_neg_001',
    titleTemplate: '北向资金大幅净流出{amount}亿元，外资避险情绪升温',
    contentTemplate: '北向资金今日净卖出{amount}亿元，创近期单日净卖出新高。外资大幅流出引发市场担忧，投资者情绪趋于谨慎。',
    category: 'market_sentiment',
    importance: 'normal',
    type: 'negative',
    effectRange: { min: -2, max: -0.5 },
    durationRange: { min: 6, max: 18 },
    marketEffectRange: { min: -1, max: -0.3 },
    sentimentEffectRange: { min: -20, max: -8 },
    source: '财经日报',
  },
  {
    id: 'sentiment_neg_002',
    titleTemplate: '市场恐慌指数飙升，投资者情绪低迷',
    contentTemplate: '市场恐慌指数(VIX)今日飙升{percent}%，显示投资者恐慌情绪加剧。市场波动加大，建议投资者保持理性，控制风险。',
    category: 'market_sentiment',
    importance: 'major',
    type: 'negative',
    effectRange: { min: -2, max: -0.5 },
    durationRange: { min: 8, max: 24 },
    marketEffectRange: { min: -1.5, max: -0.5 },
    sentimentEffectRange: { min: -25, max: -10 },
    source: '华尔街见闻',
  },
];

// 金融动态新闻模板
export const FINANCIAL_NEWS: NewsTemplate[] = [
  {
    id: 'financial_pos_001',
    titleTemplate: '央行开展MLF操作{amount}亿元，利率下调{rate}个百分点',
    contentTemplate: '中国人民银行开展中期借贷便利(MLF)操作{amount}亿元，中标利率{rate}%，较此前下调{change}个百分点。此举将降低银行资金成本，引导贷款利率下行。',
    category: 'financial',
    importance: 'major',
    type: 'positive',
    effectRange: { min: 1, max: 3 },
    durationRange: { min: 12, max: 36 },
    marketEffectRange: { min: 0.5, max: 1.5 },
    sentimentEffectRange: { min: 15, max: 25 },
    source: '金融时报',
  },
  {
    id: 'financial_pos_002',
    titleTemplate: '人民币汇率企稳回升，外资流入预期增强',
    contentTemplate: '人民币兑美元汇率今日升值{percent}%，结束此前连续下跌态势。汇率企稳有助于稳定外资流入预期，对A股市场形成支撑。',
    category: 'financial',
    importance: 'normal',
    type: 'positive',
    effectRange: { min: 0.5, max: 1.5 },
    durationRange: { min: 8, max: 24 },
    marketEffectRange: { min: 0.3, max: 0.8 },
    sentimentEffectRange: { min: 10, max: 18 },
    source: '新华财经',
  },
  {
    id: 'financial_neg_001',
    titleTemplate: '债券市场波动加剧，信用风险引发关注',
    contentTemplate: '近期债券市场波动加剧，部分企业债券价格大幅下跌。市场对信用风险的担忧上升，投资者需关注债券投资风险。',
    category: 'financial',
    importance: 'normal',
    type: 'negative',
    effectRange: { min: -1, max: -0.3 },
    durationRange: { min: 8, max: 24 },
    affectedIndustries: ['finance'],
    sentimentEffectRange: { min: -15, max: -5 },
    source: '经济观察报',
  },
];

// 所有新闻模板
export const ALL_NEWS_TEMPLATES: NewsTemplate[] = [
  ...MACRO_ECONOMY_NEWS,
  ...INDUSTRY_NEWS,
  ...COMPANY_NEWS,
  ...POLICY_NEWS,
  ...INTERNATIONAL_NEWS,
  ...MARKET_SENTIMENT_NEWS,
  ...FINANCIAL_NEWS,
];

// 新闻生成概率配置
export const NEWS_GENERATION_CONFIG = {
  // 每小时生成新闻的概率
  hourlyProbability: 0.3,
  // 各类型新闻的权重
  categoryWeights: {
    macro_economy: 10,
    industry: 25,
    company: 30,
    policy: 10,
    international: 10,
    market_sentiment: 10,
    financial: 5,
  },
  // 各重要性新闻的权重
  importanceWeights: {
    minor: 40,
    normal: 35,
    major: 20,
    critical: 5,
  },
  // 突发新闻概率
  breakingProbability: 0.1,
  // 新闻有效期范围（小时）
  expiryRange: {
    minor: { min: 2, max: 6 },
    normal: { min: 6, max: 18 },
    major: { min: 12, max: 36 },
    critical: { min: 24, max: 72 },
  },
};
